name: Node.js CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        if: contains(github.event.head_commit.message, '[run-tests]')
        run: npm test

      - name: Add database
        run: echo "MONGO_URL=${{ secrets.MONGO_URL }} >> .env"

      - name: Setup Environment Variables
        run: echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env

      # - name: Check Terraform Version
      #   run: terraform --version

      # - name: Init Terraform
      #   run: terraform init

      # - name: Set Environment Variables
      #   run: export TF_VAR_private_key_path="C:/Users/HP/Downloads/ec2-1(1).pem"

      # - name: Apply Terraform
      #   run: terraform apply -auto-approve

      - name: Build Docker Image
        run: docker build -t arvindaffan/fppso .

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Image to Docker Hub
        run: docker push arvindaffan/fppso:latest

  testing:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        if: contains(github.event.head_commit.message, '[run-tests]')
        run: npm test

  deploy:
    needs: [build, testing]
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image from Docker Hub
        run: docker pull arvindaffan/fppso:latest

      - name: Delete old Docker Container
        run: docker rm -f fppso-container

      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name fppso-container arvindaffan/fppso
